### ISSUE TITLE
I have a MissingMethodException: Method not found: 'System.Xml.XmlReaderSettings.set_MaxCharactersFromEntities' issue

### ISSUE THREAD

**Issue by twobob** [drewnoakes/xmp-core-dotnet#40]
MissingMethodException: Method not found: 'System.Xml.XmlReaderSettings.set_MaxCharactersFromEntities'.
XmpCore.Impl.XmpMetaParser.ParseXmlFromByteBuffer (XmpCore.Impl.ByteBuffer buffer, XmpCore.Options.ParseOptions options)
XmpCore.Impl.XmpMetaParser.Extract (System.Byte[] bytes, XmpCore.Options.ParseOptions options)
XmpCore.XmpMetaFactory.ExtractXDocumentFromBuffer (System.Byte[] buffer, XmpCore.Options.ParseOptions options)

I have a xmlReader.Settings.MaxCharactersFromEntities under Unity3d.
but no System.Xml.XmlReaderSettings.set_MaxCharactersFromEntities AFAIK?

Any clues?

I do a `
            byte[] imageArray = System.IO.File.ReadAllBytes(fullpath);
`
then simply   
            
            xmp = (IXmpMeta)XmpMetaFactory.ExtractXDocumentFromBuffer(imageArray);

            foreach (var property in xmp.Properties)
                Debug.Log(string.Format("Path={0} Namespace={1} Value={2}", 
            property.Path, property.Namespace, property.Value));

Is that wrong?

.net 3.5

I also tried just brute forcing the string in like

           byte[] imageArray = System.IO.File.ReadAllBytes(fullpath);

            XmlDocument docx = Twobob.BrutalXMP.ExtractXmpBytes(imageArray);

            xmp = XmpMetaFactory.ParseFromString(docx.OuterXml);

'Where the ExtractXmpBytes is tested as working okay, But I got the same error so... confuzzled

and also ` xmp = XmpMetaFactory.ParseFromBuffer(imageArray);`  fails similarly so I am guessing this is to do with the calls the XmpMetaFactory class is placing internally.

FWIW:  xmp = XmpMetaFactory.Create();  does not fail

**Comment by twobob** [comment]
okay. Cool. good to know because the metadata extractor project does EXACTLY that same thing

**Comment by kwhopper** [comment]
I setup a test on a Windows XP virtual machine with .NET Framework 3.5 installed (no 4.x bits at all). The registry reports the version as 3.5.30729.01, which coincides with .NET Framework 3.5 SP1 RTM. The environment is a console program that reads and parses a string constant containing RDF. It ran as expected with no exceptions.

The code is similar to your example:
```
static void Main(string[] args)
{
    var xmp = XmpMetaFactory.ParseFromString(SIMPLE_RDF);
    foreach (var property in xmp.Properties)
        Console.WriteLine(string.Format("Path={0} Namespace={1} Value={2}",
                            property.Path, property.Namespace, property.Value));
    Console.ReadLine();           
}
```
Do you see any issues with how I setup the test?

The 'missing' method has been available since .NET 2.0, and should exist if you have .NET Framework 3.5 installed correctly on the client machine. Are you certain the framework is installed correctly - perhaps up to at least SP1? Are you manually including other .NET Framework assemblies in your bin folder?

**Comment by kwhopper** [comment]
This feels like a local Framework issue, so closing for now. You find that it isn't feel free to comment or re-open.

**Comment by twobob** [comment]
Okay thanks
